openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: |-
    This is a ULP middleware API document to create required API's for the issuance portal
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://ulp.uniteframework.io/middleware//v1
tags:
  - name: credential
    description: Bulk AAPI to generate credential of student
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /credential/upload:
    parameters:
        - in: query
          name: type
          schema:
            type: string
            default: proofOfAssessment
          required: true
          description: The number of items to skip before starting to collect the result set.
    post:
      tags:
        - credential
      summary: bulk import student data to generate credetials
      description: process all the student records and generate crdentials of it
      operationId: importCredential
      requestBody:
        description: Create credentials for each student
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credential'
          application/xml:
            schema:
              $ref: '#/components/schemas/Credential'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Credential'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Credential'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Credential'
        '405':
          description: Invalid input
      security:
        - petstore_auth:
            - write:credential
            - read:credential
  
components:
  schemas:
    Credential:
      required:
        - name
        - photoUrls
      type: object
      properties:
        schoolDid:
          type: string
          example: DID:ULP:289347329
        schoolName:
          type: string
          example: Delhi public school
        schoolDistrict:
          type: string
          example: Delhi
        schoolState:
          type: string
          example: Delhi
        grade:
          type: string
          example: class-8
        academicYear:
          type: string
          example: 2022-2023
        issuanceDate:
          type: string
          example: ""
        expirationDate:
          type: string
          example: ""
        credentialSubject:
          type: array
          xml:
            wrapped: true
          items:
             $ref: '#/components/schemas/Credential'
      xml:
        name: credential
    credentialSubject:
      type: object
      properties:
        studentName:
          type: string
          example: ANAMIKA
        guardianName:
          type: string
          example: Rakesh
        studentId:
          type: string
          example: 236239
      xml:
        name: credentialSubject
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: '##default'
  requestBodies:
    Credential:
      description: Credentials to be issued to students
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Credential'
        application/xml:
          schema:
            $ref: '#/components/schemas/Credential'
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header